/* Generated by powerful Codeforces Tool
 * Author: PierreQi
 * Time: 2022-09-05 14:39:35
**/

//#include <bits/stdc++.h>

#include <iostream>
//#include <utility>
// #include <vector>
// #include <map>
// #include <set>
// #include <stack>
// #include <queue>
// #include <unordered_map>
// #include <unordered_set>
// #include <algorithm>


using namespace std;
#define fio ios_base::sync_with_stdio(false); cin.tie(NULL);

typedef long long ll;

int main(){
    fio;
    // cin >>
    
    // cout <<
}

