/* Generated by powerful Codeforces Tool
 * Author: PierreQi
 * Time: 2022-09-01 22:10:36
**/

//#include <bits/stdc++.h>

#include <iostream>
//#include <utility>
// #include <vector>
// #include <map>
// #include <set>
// #include <stack>
// #include <queue>
// #include <unordered_map>
// #include <unordered_set>
// #include <algorithm>


using namespace std;
#define fio ios_base::sync_with_stdio(false); cin.tie(NULL);

int main(){
    fio;
    
    int n;
    scanf("%d", &n);

    if (n == 2) printf("NO");
    else if (n % 2 == 0) printf("YES");
    else printf("NO");
}

