/* Generated by powerful Codeforces Tool
 * Author: PierreQi
 * Time: 2022-08-13 21:40:14
**/

import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.StringTokenizer;
import java.io.InputStreamReader;

public class a{

	public static void main(String[] args){
		FastScanner sc = new FastScanner();
        
        PrintWriter out = new PrintWriter(new BufferedOutputStream(System.out));        

		//-------------Your Code Here -----------------
		int weight = sc.nextInt();
        if (weight == 2) out.print("NO");
        else
            out.print(weight % 2 == 0 ? "YES":"NO");		
		//-------------Your Code Above-----------------
		out.close();
	} 

	public static class FastScanner {
        
		BufferedReader br;
        StringTokenizer st;

        public FastScanner() {
            br = new BufferedReader(new InputStreamReader(System.in));
        }

        String next() {
            while (st == null || !st.hasMoreElements()) {
                try {
                    st = new StringTokenizer(br.readLine());
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            return st.nextToken();
        }

        int nextInt() {
            return Integer.parseInt(next());
        }

        long nextLong() {
            return Long.parseLong(next());
        }

        double nextDouble() {
            return Double.parseDouble(next());
        }

        String nextLine(){
            String str = "";
            try {
                str = br.readLine();
            } catch (IOException e) {
                e.printStackTrace();
            }
            return str;
        }
    }
}
