/* Generated by powerful Codeforces Tool
 * Author: PierreQi
 * Time: 2022-08-11 10:43:35
**/

import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Collections;
import java.util.HashMap;
import java.util.StringTokenizer;
import java.io.InputStreamReader;

public class a{

	public static void main(String[] args){
		FastScanner sc = new FastScanner();
        
        PrintWriter out = new PrintWriter(new BufferedOutputStream(System.out));        

		//-------------Your Code Here -----------------

		int n = sc.nextInt();
        //name <--> score
        HashMap<String,Integer> map = new HashMap<>();        
        int[] score = new int[n];
        String[] name = new String[n];

        for(int i = 0;i < n;i++){
            name[i] = sc.next();
            score[i] = sc.nextInt();

            if (map.containsKey(name[i])){
                score[i] += map.get(name[i]);
                map.put(name[i], score[i]);

            }else{                
                map.put(name[i],score[i]);    
            }                             
        }
        
        int ans = Collections.max(map.values());

        for(int i = 0; i < n ; i ++){
			if(ans == map.get(name[i]) && score[i] >= ans){
                out.println(name[i]);                
				break;
			}
		}        
		//-------------Your Code Above-----------------
		//out.close();
	} 

	public static class FastScanner {
        
		BufferedReader br;
        StringTokenizer st;

        public FastScanner() {
            br = new BufferedReader(new InputStreamReader(System.in));
        }

        String next() {
            while (st == null || !st.hasMoreElements()) {
                try {
                    st = new StringTokenizer(br.readLine());
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            return st.nextToken();
        }

        int nextInt() {
            return Integer.parseInt(next());
        }

        long nextLong() {
            return Long.parseLong(next());
        }

        double nextDouble() {
            return Double.parseDouble(next());
        }

        String nextLine(){
            String str = "";
            try {
                str = br.readLine();
            } catch (IOException e) {
                e.printStackTrace();
            }
            return str;
        }
    }
}
